services:
  postgres:
    image: postgres:17.6-alpine
    hostname: postgres
    expose:
      - 5432
    env_file:
      - env-example-relational
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-root}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-secret}
      POSTGRES_DB: ${DATABASE_NAME:-api}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-root}"]
      interval: 5s
      timeout: 5s
      retries: 5

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    hostname: maildev
    env_file:
      - env-example-relational
    expose:
      - 1080
      - 1025

  #  Uncomment to use redis
  redis:
    image: redis:8.4-alpine
    hostname: redis
    env_file:
      - env-example-relational
    expose:
      - 6379

  api:
    build:
      context: .
      dockerfile: relational.test.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      maildev:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - 3000:3000
      - 4000:4000
    env_file:
      - env-example-relational
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test

networks:
  default:
    name: next-block-net
    external: true
