services:
  postgres:
    image: postgres:17.6-alpine
    hostname: postgres
    expose:
      - 5432
    env_file:
      - env-example-relational
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-root}"]
      interval: 5s
      timeout: 5s
      retries: 5

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    hostname: maildev
    env_file:
      - env-example-relational
    expose:
      - 1080
      - 1025

  #  Uncomment to use redis
  redis:
    image: redis:8.4-alpine
    hostname: redis
    env_file:
      - env-example-relational
    expose:
      - 6379

  app:
    build:
      context: .
      dockerfile: relational.e2e.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      maildev:
        condition: service_started
      redis:
        condition: service_started
    expose:
      - 3000
      - 4000
    env_file:
      - env-example-relational

networks:
  default:
    name: vault-net
    external: true
